import type { ApplicantRecord } from "@/components/dashboard/applicant-list";

const now = new Date();

function daysAgo(days: number) {
  return new Date(now.getTime() - days * 86_400_000).toISOString();
}

export const demoProperties = [
  {
    name: "Ridgeview 2B",
    address: "1420 Ridgeview Ave, Unit 2B",
    rent: 2450,
  },
  {
    name: "Maple Street Garden",
    address: "88 Maple Street, Unit 1",
    rent: 3100,
  },
];

export const demoApplicants: ApplicantRecord[] = [
  {
    _id: "demo-nina",
    name: "Nina Patel",
    email: "nina@example.com",
    phone: "555-0184",
    propertyAddress: demoProperties[0].address,
    propertyCity: "Queens",
    propertyState: "NY",
    propertyPostalCode: "11385",
    moveInDate: "2026-06-15",
    coApplicants: [],
    applicationSource: "Zillow",
    monthlyRent: 2450,
    monthlyIncome: 9200,
    housingSupport: "None",
    supportProgram: "",
    monthlySubsidyAmount: 0,
    tenantPortionRent: 0,
    subsidyStatus: "N/A",
    inspectionStatus: "N/A",
    residentScore: 742,
    scores: { income: 92, credit: 86, resident: 88, rentalHistory: 84, rulesCompliance: 90, timeline: 86, communication: 92, documentation: 88 },
    totalScore: 88,
    affordabilityRatio: 3.8,
    responsibleRent: 2450,
    decision: "Strong",
    redFlags: [],
    notes: ["Documents received\nGovernment ID\nProof of income\nBank statements\nLandlord reference\nCompleted application", "AI summary\nStrong affordability and complete file. Ready for owner review."],
    status: "Screening",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    _id: "demo-marcus",
    name: "Marcus Rivera",
    email: "marcus@example.com",
    phone: "555-0142",
    propertyAddress: demoProperties[0].address,
    propertyCity: "Queens",
    propertyState: "NY",
    propertyPostalCode: "11385",
    moveInDate: "",
    coApplicants: [],
    applicationSource: "Email / Manual",
    monthlyRent: 2450,
    monthlyIncome: 6100,
    housingSupport: "None",
    supportProgram: "",
    monthlySubsidyAmount: 0,
    tenantPortionRent: 0,
    subsidyStatus: "N/A",
    inspectionStatus: "N/A",
    residentScore: 680,
    scores: { income: 76, credit: 72, resident: 76, rentalHistory: 70, rulesCompliance: 70, timeline: 40, communication: 75, documentation: 42 },
    totalScore: 71,
    affordabilityRatio: 2.5,
    responsibleRent: 2450,
    decision: "Review",
    redFlags: ["Move-in timeline unclear"],
    notes: ["Missing items\nBank statements\nLandlord reference\nMove-in date", "AI summary\nGood income fit, but the file needs documents before owner review."],
    status: "New",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    _id: "demo-asha",
    name: "Asha Coleman",
    email: "asha@example.com",
    phone: "555-0199",
    propertyAddress: demoProperties[1].address,
    propertyCity: "Brooklyn",
    propertyState: "NY",
    propertyPostalCode: "11221",
    moveInDate: "2026-07-01",
    coApplicants: [],
    applicationSource: "Apartments.com",
    monthlyRent: 3100,
    monthlyIncome: 4800,
    housingSupport: "Voucher",
    supportProgram: "Housing Choice Voucher",
    monthlySubsidyAmount: 1900,
    tenantPortionRent: 1200,
    subsidyStatus: "Pending",
    inspectionStatus: "Pending",
    residentScore: 0,
    scores: { income: 82, credit: 0, resident: 0, rentalHistory: 68, rulesCompliance: 80, timeline: 76, communication: 82, documentation: 62 },
    totalScore: 74,
    affordabilityRatio: 4,
    responsibleRent: 1200,
    decision: "Review",
    redFlags: ["Voucher verification pending"],
    notes: ["Documents received\nGovernment ID\nCompleted application\nVoucher note", "Missing items\nVoucher shopping letter\nCase worker contact\nLandlord reference", "AI summary\nTenant portion appears affordable. Verify voucher packet before owner review."],
    status: "Review",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(2),
  },
  {
    _id: "demo-jon",
    name: "Jon Kim",
    email: "jon@example.com",
    phone: "555-0177",
    propertyAddress: demoProperties[1].address,
    propertyCity: "Brooklyn",
    propertyState: "NY",
    propertyPostalCode: "11221",
    moveInDate: "2026-06-01",
    coApplicants: [],
    applicationSource: "RentSpree",
    monthlyRent: 3100,
    monthlyIncome: 3900,
    housingSupport: "None",
    supportProgram: "",
    monthlySubsidyAmount: 0,
    tenantPortionRent: 0,
    subsidyStatus: "N/A",
    inspectionStatus: "N/A",
    residentScore: 610,
    scores: { income: 45, credit: 58, resident: 60, rentalHistory: 50, rulesCompliance: 55, timeline: 72, communication: 62, documentation: 56 },
    totalScore: 56,
    affordabilityRatio: 1.3,
    responsibleRent: 3100,
    decision: "Risk",
    redFlags: ["Affordability below policy", "Rental history needs review"],
    notes: ["Missing items\nBank statements\nLandlord reference", "AI summary\nManual review recommended due to affordability and incomplete references."],
    status: "Review",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(3),
  },
  {
    _id: "demo-lena",
    name: "Lena Brooks",
    email: "lena@example.com",
    phone: "555-0133",
    propertyAddress: demoProperties[0].address,
    propertyCity: "Queens",
    propertyState: "NY",
    propertyPostalCode: "11385",
    moveInDate: "2026-06-20",
    coApplicants: [],
    applicationSource: "TurboTenant",
    monthlyRent: 2450,
    monthlyIncome: 7800,
    housingSupport: "None",
    supportProgram: "",
    monthlySubsidyAmount: 0,
    tenantPortionRent: 0,
    subsidyStatus: "N/A",
    inspectionStatus: "N/A",
    residentScore: 715,
    scores: { income: 86, credit: 82, resident: 84, rentalHistory: 78, rulesCompliance: 84, timeline: 84, communication: 88, documentation: 72 },
    totalScore: 82,
    affordabilityRatio: 3.2,
    responsibleRent: 2450,
    decision: "Strong",
    redFlags: [],
    notes: ["Documents received\nGovernment ID\nProof of income\nCompleted application", "Missing items\nLandlord reference", "Generated message\nPlease send your prior landlord reference when available."],
    status: "Screening",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
];
